version: '3.9'

services:
    db:
        image: postgres
        restart: always
        shm_size: 128mb
        hostname: db
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: root
            POSTGRES_DB: autoscaler
        ports:
            - "5432:5432"
    autoscaler:
        build:
            context: .
            no_cache: false
            
        restart: always
        environment:
            Autoscaler__Database__Hostname: db
            Autoscaler__Runner__Start: true
            Autoscaler__Apis__Forecaster__Mock: true
            Autoscaler__Apis__Kubernetes__Mock: true
            Autoscaler__Apis__Prometheus__Mock: true
            Autoscaler__Port: 8081
            Logging__LogLevel__Autoscaler: debug
        depends_on:
            -   db
        
        ports:
            - "8081:8081"
