version: '3.9'

services:
    db:
        image: postgres
        restart: always
        shm_size: 128mb
        hostname: db
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: root
            POSTGRES_DB: autoscaler
        ports:
            - "5432:5432"
    autoscaler:
        image: ghcr.io/aau-p9s/autoscaler:test
        restart: always
        environment:
            Autoscaler__Database__Hostname: 10.225.171.54
            Autoscaler__Runner__Start: true
            Autoscaler__Apis__Forecaster__Url: http://10.225.171.54:8080
            Autoscaler__Apis__Forecaster__Mock: false
            Autoscaler__Apis__Kubernetes__Mock: true
            Autoscaler__Apis__Prometheus__Mock: true
        
        ports:
            - "8081:8081"