version: '3.9'

services:
    db:
        image: postgres
        restart: always
        shm_size: 128mb
        hostname: db
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: root
            POSTGRES_DB: autoscaler
        ports:
            - "5432:5432"
    autoscaler:
        image: ghcr.io/aau-p9s/autoscaler:latest
        restart: always
        environment:
            AUTOSCALER__PGSQL__ADDR: db
            AUTOSCALER__STARTRUNNER: false
        
        ports:
            - "8080:8080"