version: '3.9'

services:
    db:
        image: postgres
        restart: always
        shm_size: 128mb
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: root
            POSTGRES_DB: autoscaler
        ports:
            - "5432:5432"
