name: Docker API Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AUTOSCALER__PGSQL__ADDR: postgres
  AUTOSCALER__PGSQL__PASSWORD: password
  AUTOSCALER__HOST: 0.0.0.0
  AUTOSCALER__PORT: 8080

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      image: postgres
      env:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: root
        POSTGRES_DB: autoscaler
    steps:
      - name: checkout repo
        uses: actions/checkout@v4.1.1
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8"
      - name: migrate db
        run: dotnet run Autoscaler.DbUp
      - name: run docker
        run: docker run -d $(docker build . -q)
      - name: test API
        run: ./.github/workflows/api_test.sh "$AUTOSCALER_HOST:$AUTOSCALER_PORT"