name: Dotnet Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AUTOSCALER_PGSQL_ADDR: postgres
  AUTOSCALER_PGSQL_PASSWORD: password

jobs:
  test:
    runs-on: ubuntu-latest
    services: 
      image: postgres
      env:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: root
        POSTGRES_DB: autoscaler
    steps:
      - name: checkout repo
        uses: actions/checkout
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8"
      - name: migrate db
        run: dotnet run Autoscaler.DbUp
      - name: run docker
        run: docker run -d $(docker build . -q)
      - name: test API
        run: ./.github/workflows/api_test.sh