name: Docker API Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  Autoscaler__Database__Hostname: localhost
  Autoscaler__Database__Password: password
  Autoscaler__Database__User: root
  Autoscaler__Host: 0.0.0.0
  Autoscaler__Port: 8081

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4.1.1
      - name: build docker image
        run: docker build . -t ghcr.io/aau-p9s/autoscaler:test
      - name: run db
        run: docker compose up db -d 
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8"
      - name: migrate db
        run: dotnet run --project Autoscaler.DbUp
      - name: run autoscaler
        run: docker compose up autoscaler -d
      - name: sleep a bit
        run: sleep 5
      - name: test API
        run: bash .github/workflows/api_test.sh "$Autoscaler__Host:$Autoscaler__Port"
      - name: reverse API test (check if test fails due to changes)
        run: (! bash .github/workflows/api_test.sh "$Autoscaler__Host:$Autoscaler__Port")
