name: Docker API Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AUTOSCALER__PGSQL__ADDR: postgres
  AUTOSCALER__PGSQL__PASSWORD: password
  AUTOSCALER__PGSQL__USER: root
  AUTOSCALER__HOST: 0.0.0.0
  AUTOSCALER__PORT: 8080

jobs:
  test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:8.0
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: root
          POSTGRES_DB: autoscaler
    steps:
      - name: checkout repo
        uses: actions/checkout@v4.1.1
      - name: migrate db
        run: dotnet run --project Autoscaler.DbUp
      - name: setup docker
        run: sudo apt update && sudo apt install docker.io
      - name: run docker
        run: docker run -d $(docker build . -q)
      - name: test API
        run: bash .github/workflows/api_test.sh "$AUTOSCALER__HOST:$AUTOSCALER__PORT"