name: Docker API Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AUTOSCALER__PGSQL__ADDR: localhost
  AUTOSCALER__PGSQL__PASSWORD: password
  AUTOSCALER__PGSQL__USER: root
  AUTOSCALER__HOST: 0.0.0.0
  AUTOSCALER__PORT: 8080

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: root
          POSTGRES_DB: autoscaler
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5 
    steps:
      - name: checkout repo
        uses: actions/checkout@v4.1.1
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8"
      - name: migrate db
        run: dotnet run --project Autoscaler.DbUp
      - name: run docker
        run: docker run -d -p 8080:8080 -e "AUTOSCALER__PGSQL__ADDR=postgres" $(docker build . -q)
      - name: test API
        run: bash .github/workflows/api_test.sh "$AUTOSCALER__HOST:$AUTOSCALER__PORT"